const ERROR_CODES = Object.freeze({
  VALIDATION_ERROR: "VALIDATION_ERROR",

  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",

  NOT_FOUND: "NOT_FOUND",

  USER_NOT_FOUND: "USER_NOT_FOUND",
  SHIPMENT_NOT_FOUND: "SHIPMENT_NOT_FOUND",
  HUB_NOT_FOUND: "HUB_NOT_FOUND",
  COMPLAINT_NOT_FOUND: "COMPLAINT_NOT_FOUND",
  NOTIFICATION_NOT_FOUND: "NOTIFICATION_NOT_FOUND",
  DELIVERY_ASSIGNMENT_NOT_FOUND: "DELIVERY_ASSIGNMENT_NOT_FOUND",

  INVALID_STATUS_TRANSITION: "INVALID_STATUS_TRANSITION",
  INVALID_ASSIGNMENT_TRANSITION: "INVALID_ASSIGNMENT_TRANSITION",

  DUPLICATE_RESOURCE: "DUPLICATE_RESOURCE",
  BUSINESS_RULE_VIOLATION: "BUSINESS_RULE_VIOLATION",

  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
});

module.exports = ERROR_CODES;
